---
# This playbook install a basic user with the login keys
- name: create drac0
  tags: 
   - configuration
   - security
  user: name=splunk-admin shell=/bin/bash state=present password={{user_pass}}

- name: copy splunk-admin authorize_keys
  authorized_key: user=splunk-admin key="{{ lookup('file', 'home/splunk-admin/.ssh/splunk-admin.pub') }}"
  tags:
   - configuration
   - security



