---
# playbook copies over indexes.conf for the indexers

- name: copy indexes.conf 
  tags:
   - install
  copy: src=opt/splunk/etc/system/local/indexes.yml dest=/opt/splunk/etc/system/local owner=splunk group=splunk mode=755
notify: restart splunk
